"""optional best of

Revision ID: 0b8090b93ad8
Revises: cce6eb0281da
Create Date: 2024-10-19 19:28:21.606550

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b8090b93ad8"
down_revision: Union[str, None] = "cce6eb0281da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("matches", "best_of", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("matches_region_id_fkey", "matches", type_="foreignkey")
    op.drop_column("matches", "region_id")
    op.drop_table("regions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches",
        sa.Column("region_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "matches_region_id_fkey", "matches", "regions", ["region_id"], ["id"]
    )
    op.alter_column("matches", "best_of", existing_type=sa.INTEGER(), nullable=False)
    op.create_table(
        "regions",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name_short", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="regions_pkey"),
    )
    # ### end Alembic commands ###
