"""add match type

Revision ID: cce6eb0281da
Revises: d8b43a5996df
Create Date: 2024-10-01 19:40:00.817750

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cce6eb0281da"
down_revision: Union[str, None] = "ea2cdf2c04ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches", sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "type")
    # ### end Alembic commands ###
